name: news_app_with_structure
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.2
  bloc: ^6.1.1
  rxdart: ^0.25.0
  equatable: ^1.2.6
  dio: ^3.0.10
  introduction_screen: ^1.0.9
  flutter_svg: ^0.19.1
  eva_icons_flutter: ^2.0.1
  get_it: ^5.0.5
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  intl_utils: ^1.9.0
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: Localization